theme="blackburn"
languageCode = "en-us"
builddrafts = false

baseurl = "http://github.com/compumetrika/homepage/"
title = "Compumetrika"
author = "Nathan M. Palmer"
# Shown in the side menu
copyright = "&copy; 2017. All rights reserved."
canonifyurls = true
paginate = 10
publishdir = "docs"

[indexes]
  tag = "tags"
  topic = "topics"

[params]
  # Shown in the home page
  subtitle = "Personal website of Nathan M. Palmer"
  brand = "By computing<br>we find out"
  #subtitle = "By computing we find out"
  #brand = "Nathan M.<br>Palmer, PhD"
  #googleAnalytics =  "*" #"Your Google Analytics tracking ID"
  #disqus = "*" #"Your Disqus shortname"
  # CSS name for highlight.js
  highlightjs = "androidstudio"
  dateFormat = "02 Jan 2006, 15:04"
  # Include any custom CSS and/or JS files
  # (relative to /static folder)
  custom_css = ["css/my.css"]
  custom_js = ["js/my.js"]

[menu]
  # Shown in the side menu.
  [[menu.main]]
    name = "Home"
    pre = "<i class='fa fa-home fa-fw'></i>"
    weight = 0
    identifier = "home"
    url = "/"
  [[menu.main]]
    name = "About"
    pre = "<i class='fa fa-user fa-fw'></i>"
    weight = 1
    identifier = "about"
    url = "/pages/about"
  [[menu.main]]
    name = "Research"
    pre = "<i class='fa fa-area-chart fa-fw'></i>"
    weight = 2
    identifier = "research"
    url = "/pages/research"
  [[menu.main]]
    name = "Notebooks"
    pre = "<i class='fa fa-archive fa-fw'></i>"
    weight = 3
    identifier = "notebook"
    url = "/pages/notebooks"
  [[menu.main]]
    name = "Blog"
    pre = "<i class='fa fa-list fa-fw'></i>"
    weight = 4
    identifier = "post"
    url = "/post/"



[social]
  # Link your social networking accounts to the side menu
  # by entering your username or ID.

  # SNS microblogging
  #twitter = "StochasticNate"
  #gnusocial = "*" # Specify href (e.g. https://quitter.se/yourusername)
  #facebook = "*"
  #googleplus = "*"
  #weibo = "*"
  #tumblr = "*"

  # SNS photo/video sharing
  #instagram = "*"
  #flickr = "*"
  #pinterest = "*"
  #youtube = "*"
  #vimeo = "*"
  #vine = "*"
  #slideshare = "*"

  # SNS career oriented
  linkedin = "nathan-m-palmer"
  #xing = "*"

  # SNS news
  #reddit = "*"
  #hackernews = "*"

  # Techie
  github = "compumetrika"
  #bitbucket = "*"
  #stackoverflow = "*"
  #serverfault = "*"

  # Gaming
  #steam = "*"
  #mobygames = "*"

  # Music
  #lastfm = "*"
  #discogs = "*"

  # Other
  #keybase = "*"

